### ISSUE TITLE
send_message not working

### ISSUE THREAD

**Issue by obrennomartins** [CNajm/Sych-WhatsApp#2]
The method `send_message` is returning `True` even though the message is not really sent.

**Comment by cnajm** [comment]
Hi @martinsbe, could you provide more context as to how you're calling/running the method(s)? I wasn't able to reproduce the bug on 2 OSs.

I've also replaced `send_message` with a basic wrapper function that tries to confirm that the message has been sent, but this again depends on how the bug is manifesting for you.
